import { RolePermissions, ThresholdSettings, DataCenter } from '../types';

export const DEFAULT_ROLE_PERMISSIONS: Record<string, RolePermissions> = {
  Admin: {
    canAddServer: true,
    canEditServer: true,
    canDeleteServer: true,
    canAckAlerts: true, // Admin ONLY acknowledges
    canResolveAlerts: false, // Admin does NOT resolve alerts
    canEditThresholds: true,
    canManageTokens: true,
    canTriggerFailover: true,
    canToggleDcMaintenance: true,
    canViewAuditLogs: true,
    canManageUsers: true,
    canExportReports: true,
  },
  Operator: {
    canAddServer: false,
    canEditServer: false,
    canDeleteServer: false,
    canAckAlerts: false, // Admin only acknowledges
    canResolveAlerts: true, // Operator resolves
    canEditThresholds: false,
    canManageTokens: false,
    canTriggerFailover: false,
    canToggleDcMaintenance: false,
    canViewAuditLogs: false,
    canManageUsers: false,
    canExportReports: true,
  },
  User: {
    canAddServer: false,
    canEditServer: false,
    canDeleteServer: false,
    canAckAlerts: false,
    canResolveAlerts: false,
    canEditThresholds: false,
    canManageTokens: false,
    canTriggerFailover: false,
    canToggleDcMaintenance: false,
    canViewAuditLogs: false,
    canManageUsers: false,
    canExportReports: true,
  },
};

export const DEFAULT_THRESHOLDS: ThresholdSettings = {
  diskUsageLimitPct: 85,
  cpuUsageLimitPct: 80,
  memoryUsageLimitPct: 80,
  backupFailureTimeoutHours: 24,
  emailAlertsEnabled: true,
  slackAlertsEnabled: false,
  smsAlertsEnabled: true,
  alertRecipientEmails: ['noc-alerts@itdb.gov.et', 'sysadmin@itdb.gov.et'],
  pingIntervalSeconds: 30,
  ipRestrictionEnabled: true,
  allowedSubnet: '10.200.0.0/16',
};

export const DATA_CENTERS_LIST: DataCenter[] = [
  {
    id: 'DC-01',
    code: 'ADD-01',
    name: 'Addis Ababa Central DC',
    city: 'Addis Ababa',
    region: 'Central Hub',
    tier: 'Tier IV',
    status: 'Healthy',
    primaryRole: 'Primary Government Core Infrastructure',
    serverCount: 148,
    rackCount: 24,
    totalCapacityKw: 850,
    currentPowerUsageKw: 412,
    pue: 1.21,
    temperatureC: 19.4,
    humidityPct: 45,
    networkLatencyMs: 1.2,
    bandwidthGbps: 100,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Top Secret Level 4',
    ipSubnet: '10.200.4.0/22',
  },
  {
    id: 'DC-02',
    code: 'DIR-01',
    name: 'Dire Dawa East Hub',
    city: 'Dire Dawa',
    region: 'Eastern Hub',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Eastern Regional Replication & Trade Gateway',
    serverCount: 82,
    rackCount: 14,
    totalCapacityKw: 450,
    currentPowerUsageKw: 215,
    pue: 1.28,
    temperatureC: 20.2,
    humidityPct: 48,
    networkLatencyMs: 3.8,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.8.0/22',
  },
  {
    id: 'DC-03',
    code: 'BHR-01',
    name: 'Bahir Dar North DC',
    city: 'Bahir Dar',
    region: 'Amhara Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Northern Region Backup & Analytics',
    serverCount: 76,
    rackCount: 12,
    totalCapacityKw: 400,
    currentPowerUsageKw: 198,
    pue: 1.26,
    temperatureC: 19.8,
    humidityPct: 44,
    networkLatencyMs: 4.1,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.12.0/22',
  },
  {
    id: 'DC-04',
    code: 'HAW-01',
    name: 'Hawassa South DC',
    city: 'Hawassa',
    region: 'Sidama Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Southern Industrial & Trade Infrastructure',
    serverCount: 64,
    rackCount: 10,
    totalCapacityKw: 350,
    currentPowerUsageKw: 172,
    pue: 1.24,
    temperatureC: 19.1,
    humidityPct: 42,
    networkLatencyMs: 4.5,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.16.0/22',
  },
  {
    id: 'DC-05',
    code: 'MEK-01',
    name: 'Mekelle North-East Hub',
    city: 'Mekelle',
    region: 'Tigray Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Highland Disaster Recovery & Telemetry Hub',
    serverCount: 58,
    rackCount: 10,
    totalCapacityKw: 320,
    currentPowerUsageKw: 148,
    pue: 1.29,
    temperatureC: 20.8,
    humidityPct: 46,
    networkLatencyMs: 5.2,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.20.0/22',
  },
  {
    id: 'DC-06',
    code: 'ADA-01',
    name: 'Adama Express DC',
    city: 'Adama',
    region: 'Oromia Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Transit Corridor Network Node',
    serverCount: 52,
    rackCount: 8,
    totalCapacityKw: 280,
    currentPowerUsageKw: 136,
    pue: 1.23,
    temperatureC: 19.5,
    humidityPct: 43,
    networkLatencyMs: 2.1,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.24.0/22',
  },
  {
    id: 'DC-07',
    code: 'JIM-01',
    name: 'Jimma South-West DC',
    city: 'Jimma',
    region: 'South-West Hub',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'South-Western Agricultural & Portal Hub',
    serverCount: 44,
    rackCount: 8,
    totalCapacityKw: 240,
    currentPowerUsageKw: 114,
    pue: 1.27,
    temperatureC: 20.1,
    humidityPct: 47,
    networkLatencyMs: 5.8,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.28.0/22',
  },
  {
    id: 'DC-08',
    code: 'GON-01',
    name: 'Gondar Heritage Node',
    city: 'Gondar',
    region: 'North-West Hub',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Northern Auxiliary Disaster Standby',
    serverCount: 38,
    rackCount: 6,
    totalCapacityKw: 200,
    currentPowerUsageKw: 92,
    pue: 1.25,
    temperatureC: 19.3,
    humidityPct: 41,
    networkLatencyMs: 6.2,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.32.0/22',
  },
  {
    id: 'DC-09',
    code: 'DES-01',
    name: 'Dessie Central-North DC',
    city: 'Dessie',
    region: 'Wollo Basin',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Mountain Pass Telemetry & Transit Relaying',
    serverCount: 32,
    rackCount: 6,
    totalCapacityKw: 180,
    currentPowerUsageKw: 84,
    pue: 1.26,
    temperatureC: 19.7,
    humidityPct: 44,
    networkLatencyMs: 4.9,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.36.0/22',
  },
  {
    id: 'DC-10',
    code: 'JIG-01',
    name: 'Jigjiga Somali Hub',
    city: 'Jigjiga',
    region: 'Somali Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Border Gateway & Customs Replication',
    serverCount: 36,
    rackCount: 6,
    totalCapacityKw: 200,
    currentPowerUsageKw: 96,
    pue: 1.31,
    temperatureC: 21.4,
    humidityPct: 50,
    networkLatencyMs: 7.1,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.40.0/22',
  },
];
