import {
  Server,
  Alert,
  AuditLog,
  SystemLog,
  ThresholdSettings,
  UserProfile,
  ActivityItem,
  TelemetryPoint,
  BackupHistoryPoint,
  DataCenter,
} from '../types';

export const INITIAL_DATA_CENTERS: DataCenter[] = [
  {
    id: 'DC-01',
    code: 'ADD-01',
    name: 'Addis Ababa Central DC',
    city: 'Addis Ababa',
    region: 'Central Hub',
    tier: 'Tier IV',
    status: 'Healthy',
    primaryRole: 'Core Government Portal & National Services Hub',
    serverCount: 32,
    rackCount: 18,
    totalCapacityKw: 450,
    currentPowerUsageKw: 280,
    pue: 1.22,
    temperatureC: 19.4,
    humidityPct: 44,
    networkLatencyMs: 1.2,
    bandwidthGbps: 100,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 1,
    coolingStatus: 'Optimal',
    securityZone: 'Top Secret Level 4',
    ipSubnet: '10.200.1.0/24',
  },
  {
    id: 'DC-02',
    code: 'BOL-02',
    name: 'Bole Innovation DC',
    city: 'Addis Ababa',
    region: 'Central Hub',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'High-Compute AI & Public Telemetry Cluster',
    serverCount: 24,
    rackCount: 12,
    totalCapacityKw: 380,
    currentPowerUsageKw: 240,
    pue: 1.28,
    temperatureC: 20.2,
    humidityPct: 46,
    networkLatencyMs: 1.5,
    bandwidthGbps: 40,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.2.0/24',
  },
  {
    id: 'DC-03',
    code: 'HAW-03',
    name: 'Hawassa Industrial DC',
    city: 'Hawassa',
    region: 'Southern Region',
    tier: 'Tier III',
    status: 'Warning',
    primaryRole: 'Cloud Storage & Regional Healthcare Records',
    serverCount: 16,
    rackCount: 8,
    totalCapacityKw: 260,
    currentPowerUsageKw: 195,
    pue: 1.34,
    temperatureC: 23.8,
    humidityPct: 52,
    networkLatencyMs: 8.4,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 2,
    coolingStatus: 'Degraded',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.3.0/24',
  },
  {
    id: 'DC-04',
    code: 'DIR-04',
    name: 'Dire Dawa Eastern DC',
    city: 'Dire Dawa',
    region: 'Eastern Gateway',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Customs, Logistics & Eastern Regional Services',
    serverCount: 12,
    rackCount: 6,
    totalCapacityKw: 200,
    currentPowerUsageKw: 110,
    pue: 1.31,
    temperatureC: 21.0,
    humidityPct: 41,
    networkLatencyMs: 12.2,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Normal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.4.0/24',
  },
  {
    id: 'DC-05',
    code: 'ADA-05',
    name: 'Adama Cyber DC (DR-1)',
    city: 'Adama',
    region: 'Disaster Recovery Primary',
    tier: 'Tier IV',
    status: 'Healthy',
    primaryRole: 'Hot Standby Disaster Recovery & Mirroring Site 1',
    serverCount: 18,
    rackCount: 10,
    totalCapacityKw: 400,
    currentPowerUsageKw: 210,
    pue: 1.24,
    temperatureC: 19.8,
    humidityPct: 45,
    networkLatencyMs: 4.1,
    bandwidthGbps: 100,
    backupGeneratorStatus: 'Active Testing',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Top Secret Level 4',
    ipSubnet: '10.200.5.0/24',
  },
  {
    id: 'DC-06',
    code: 'BAH-06',
    name: 'Bahir Dar Northern DC',
    city: 'Bahir Dar',
    region: 'Northern Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Northern Government Administration & Tech Hub',
    serverCount: 14,
    rackCount: 7,
    totalCapacityKw: 220,
    currentPowerUsageKw: 130,
    pue: 1.29,
    temperatureC: 20.5,
    humidityPct: 48,
    networkLatencyMs: 14.6,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 1,
    coolingStatus: 'Normal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.6.0/24',
  },
  {
    id: 'DC-07',
    code: 'MEK-07',
    name: 'Mekelle Enterprise DC',
    city: 'Mekelle',
    region: 'Northern Region',
    tier: 'Tier III',
    status: 'Warning',
    primaryRole: 'Regional Enterprise Telemetry & Civil Database',
    serverCount: 10,
    rackCount: 6,
    totalCapacityKw: 180,
    currentPowerUsageKw: 145,
    pue: 1.36,
    temperatureC: 22.4,
    humidityPct: 50,
    networkLatencyMs: 18.2,
    bandwidthGbps: 10,
    backupGeneratorStatus: 'Maintenance',
    activeAlertsCount: 1,
    coolingStatus: 'Normal',
    securityZone: 'Restricted Level 3',
    ipSubnet: '10.200.7.0/24',
  },
  {
    id: 'DC-08',
    code: 'JIM-08',
    name: 'Jimma Science DC',
    city: 'Jimma',
    region: 'Western Region',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Western Research Backbone & Agricultural Telemetry',
    serverCount: 11,
    rackCount: 6,
    totalCapacityKw: 190,
    currentPowerUsageKw: 105,
    pue: 1.30,
    temperatureC: 20.1,
    humidityPct: 49,
    networkLatencyMs: 11.5,
    bandwidthGbps: 20,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Normal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.8.0/24',
  },
  {
    id: 'DC-09',
    code: 'BIS-09',
    name: 'Bishoftu Secure DC',
    city: 'Bishoftu',
    region: 'Central Security Zone',
    tier: 'Tier IV',
    status: 'Healthy',
    primaryRole: 'Government Financial Ledger & Encryption Vault',
    serverCount: 15,
    rackCount: 8,
    totalCapacityKw: 350,
    currentPowerUsageKw: 190,
    pue: 1.21,
    temperatureC: 18.9,
    humidityPct: 42,
    networkLatencyMs: 3.2,
    bandwidthGbps: 100,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Optimal',
    securityZone: 'Top Secret Level 4',
    ipSubnet: '10.200.9.0/24',
  },
  {
    id: 'DC-10',
    code: 'ARB-10',
    name: 'Arba Minch DC (DR-2)',
    city: 'Arba Minch',
    region: 'Southern Edge DR-2',
    tier: 'Tier III',
    status: 'Healthy',
    primaryRole: 'Geographically Isolated Cold Archive & Edge DR-2',
    serverCount: 8,
    rackCount: 5,
    totalCapacityKw: 160,
    currentPowerUsageKw: 82,
    pue: 1.33,
    temperatureC: 21.2,
    humidityPct: 47,
    networkLatencyMs: 16.8,
    bandwidthGbps: 10,
    backupGeneratorStatus: 'Standby Ready',
    activeAlertsCount: 0,
    coolingStatus: 'Normal',
    securityZone: 'Standard Level 2',
    ipSubnet: '10.200.10.0/24',
  },
];

export const INITIAL_SERVERS: Server[] = [
  {
    id: 'srv-001',
    name: 'gov-portal-prod-01',
    ipAddress: '192.168.1.101',
    type: 'Web',
    os: 'Linux',
    location: 'DC-Addis-Alpha',
    department: 'Ministry of Innovation & Tech',
    criticality: 'High',
    owner: 'Abebe Bikila',
    cpuUsage: 42,
    memoryUsage: 68,
    diskUsage: 88, // > 85% threshold -> triggers disk alert!
    uptimeDays: 142,
    lastBootTime: '2026-03-17 08:30:00',
    networkStatus: 'Online',
    healthStatus: 'Warning',
    agentToken: 'agt_tok_8942a1f09c8e',
    lastBackupTime: '2026-08-06 02:00:00',
    backupStatus: 'Success',
    backupType: 'Full',
    backupSizeGB: 245.8,
    backupLocation: '/mnt/backups/gov-portal-01',
  },
  {
    id: 'srv-002',
    name: 'fin-db-cluster-node2',
    ipAddress: '192.168.1.133',
    type: 'Database',
    os: 'Linux',
    location: 'DC-Addis-Beta',
    department: 'Ministry of Finance',
    criticality: 'High',
    owner: 'Tizita Zewdu',
    cpuUsage: 94, // High CPU -> triggers critical alert
    memoryUsage: 89,
    diskUsage: 76,
    uptimeDays: 28,
    lastBootTime: '2026-07-09 14:15:22',
    networkStatus: 'Online',
    healthStatus: 'Critical',
    agentToken: 'agt_tok_3411b77f01aa',
    lastBackupTime: '2026-08-05 01:00:00',
    backupStatus: 'Failed', // Backup failure alert
    backupType: 'Incremental',
    backupSizeGB: 812.4,
    backupLocation: 's3://gov-finance-backups/node2',
  },
  {
    id: 'srv-003',
    name: 'tax-app-win-01',
    ipAddress: '192.168.1.132',
    type: 'Application',
    os: 'Windows',
    location: 'DC-Addis-Alpha',
    department: 'Revenue Authority',
    criticality: 'High',
    owner: 'Kassahun Yimer',
    cpuUsage: 65,
    memoryUsage: 72,
    diskUsage: 61,
    uptimeDays: 61,
    lastBootTime: '2026-06-06 09:00:00',
    networkStatus: 'Degraded',
    healthStatus: 'Warning',
    agentToken: 'agt_tok_9021dd510b33',
    lastBackupTime: '2026-08-06 03:30:00',
    backupStatus: 'Success',
    backupType: 'Incremental',
    backupSizeGB: 120.5,
    backupLocation: 'D:\\Backups\\TaxApp',
  },
  {
    id: 'srv-004',
    name: 'health-records-file01',
    ipAddress: '192.168.2.45',
    type: 'File',
    os: 'Windows',
    location: 'DC-Hawassa-1',
    department: 'Ministry of Health',
    criticality: 'High',
    owner: 'Dr. Meron Hailu',
    cpuUsage: 28,
    memoryUsage: 54,
    diskUsage: 91, // Disk > 85% alert
    uptimeDays: 210,
    lastBootTime: '2026-01-08 11:20:00',
    networkStatus: 'Online',
    healthStatus: 'Warning',
    agentToken: 'agt_tok_1109ff8271ab',
    lastBackupTime: '2026-08-06 00:15:00',
    backupStatus: 'Success',
    backupType: 'Full',
    backupSizeGB: 1850.0,
    backupLocation: '\\\\nas01\\health\\backups',
  },
  {
    id: 'srv-005',
    name: 'ethio-dns-core-01',
    ipAddress: '10.0.0.53',
    type: 'DNS',
    os: 'Linux',
    location: 'DC-Addis-Alpha',
    department: 'Ethio Telecom / IT Core',
    criticality: 'High',
    owner: 'Tewodros Gebre',
    cpuUsage: 18,
    memoryUsage: 35,
    diskUsage: 22,
    uptimeDays: 412,
    lastBootTime: '2025-06-20 04:00:00',
    networkStatus: 'Online',
    healthStatus: 'Operational',
    agentToken: 'agt_tok_5541ee0021bb',
    lastBackupTime: '2026-08-06 04:00:00',
    backupStatus: 'Success',
    backupType: 'Incremental',
    backupSizeGB: 12.2,
    backupLocation: '/var/backups/dns',
  },
  {
    id: 'srv-006',
    name: 'mail-gov-relay-02',
    ipAddress: '192.168.1.200',
    type: 'Mail',
    os: 'Linux',
    location: 'DC-Addis-Beta',
    department: 'Government Communications',
    criticality: 'Medium',
    owner: 'Solomon Worku',
    cpuUsage: 88,
    memoryUsage: 81,
    diskUsage: 79,
    uptimeDays: 14,
    lastBootTime: '2026-07-23 18:40:00',
    networkStatus: 'Online',
    healthStatus: 'Warning',
    agentToken: 'agt_tok_7722cc990011',
    lastBackupTime: '2026-08-06 02:45:00',
    backupStatus: 'Success',
    backupType: 'Incremental',
    backupSizeGB: 410.0,
    backupLocation: '/backup/mail/relay02',
  },
  {
    id: 'srv-007',
    name: 'edu-portal-win-02',
    ipAddress: '192.168.3.12',
    type: 'Web',
    os: 'Windows',
    location: 'DC-Adama-01',
    department: 'Ministry of Education',
    criticality: 'Medium',
    owner: 'Bethlehem Tadesse',
    cpuUsage: 33,
    memoryUsage: 48,
    diskUsage: 55,
    uptimeDays: 85,
    lastBootTime: '2026-05-13 10:10:00',
    networkStatus: 'Online',
    healthStatus: 'Operational',
    agentToken: 'agt_tok_6611aa883311',
    lastBackupTime: '2026-08-06 01:30:00',
    backupStatus: 'Success',
    backupType: 'Full',
    backupSizeGB: 320.0,
    backupLocation: 'E:\\EduPortal\\Backups',
  },
  {
    id: 'srv-008',
    name: 'police-cad-db-01',
    ipAddress: '192.168.4.99',
    type: 'Database',
    os: 'Linux',
    location: 'DC-Addis-Alpha',
    department: 'Federal Police Commission',
    criticality: 'High',
    owner: 'Commander Girma',
    cpuUsage: 91,
    memoryUsage: 93,
    diskUsage: 89,
    uptimeDays: 9,
    lastBootTime: '2026-07-28 03:00:00',
    networkStatus: 'Online',
    healthStatus: 'Critical',
    agentToken: 'agt_tok_9988ff442211',
    lastBackupTime: '2026-08-04 12:00:00', // > 24 hours ago! Backup delayed alert
    backupStatus: 'Failed',
    backupType: 'Full',
    backupSizeGB: 1240.0,
    backupLocation: '/opt/police_cad/backups',
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-101',
    serverId: 'srv-002',
    serverName: 'fin-db-cluster-node2',
    ipAddress: '192.168.1.133',
    title: 'High CPU Utilization Threshold Exceeded',
    description: 'CPU Usage sustained at 94% (Limit: 80%). Risk of query degradation or timeout on core transaction DB.',
    metric: 'CPU',
    value: '94%',
    threshold: '80%',
    severity: 'Critical',
    status: 'Active',
    timestamp: '2026-08-06T04:12:00-07:00',
  },
  {
    id: 'alt-102',
    serverId: 'srv-002',
    serverName: 'fin-db-cluster-node2',
    ipAddress: '192.168.1.133',
    title: 'Incremental Backup Failed',
    description: 'Backup agent reported error: Connection lost to remote repository s3://gov-finance-backups/node2.',
    metric: 'Backup',
    value: 'Failed',
    threshold: 'Success within 24h',
    severity: 'Critical',
    status: 'Active',
    timestamp: '2026-08-06T03:45:00-07:00',
  },
  {
    id: 'alt-103',
    serverId: 'srv-004',
    serverName: 'health-records-file01',
    ipAddress: '192.168.2.45',
    title: 'Disk Usage Space Warning (>85%)',
    description: 'Volume /dev/sdb1 disk utilization reached 91% (Threshold: 85%). Free space remaining: 166 GB.',
    metric: 'Disk',
    value: '91%',
    threshold: '85%',
    severity: 'Warning',
    status: 'Active',
    timestamp: '2026-08-06T02:30:00-07:00',
  },
  {
    id: 'alt-104',
    serverId: 'srv-001',
    serverName: 'gov-portal-prod-01',
    ipAddress: '192.168.1.101',
    title: 'Disk Usage Space Warning (>85%)',
    description: 'Root partition disk usage reached 88% (Threshold: 85%). Log rotation recommended.',
    metric: 'Disk',
    value: '88%',
    threshold: '85%',
    severity: 'Warning',
    status: 'Acknowledged',
    timestamp: '2026-08-06T01:15:00-07:00',
    acknowledgedBy: 'Tizita Zewdu (Admin)',
    acknowledgedAt: '2026-08-06T01:40:00-07:00',
  },
  {
    id: 'alt-105',
    serverId: 'srv-008',
    serverName: 'police-cad-db-01',
    ipAddress: '192.168.4.99',
    title: 'Backup Age Threshold Exceeded (>24h)',
    description: 'Last successful backup was recorded 41 hours ago. Automatic snapshot schedule halted.',
    metric: 'Backup',
    value: '41h ago',
    threshold: '24.0h',
    severity: 'Critical',
    status: 'Active',
    timestamp: '2026-08-05T20:00:00-07:00',
  },
  {
    id: 'alt-106',
    serverId: 'srv-003',
    serverName: 'tax-app-win-01',
    ipAddress: '192.168.1.132',
    title: 'Network Interface Packet Loss',
    description: 'Network packet drop rate elevated to 4.2% on Ethernet 0. High latency reported by health check.',
    metric: 'Network',
    value: '4.2% loss',
    threshold: '1.0% loss',
    severity: 'Warning',
    status: 'Resolved',
    timestamp: '2026-08-05T14:22:00-07:00',
    acknowledgedBy: 'Kassahun Yimer',
    acknowledgedAt: '2026-08-05T14:30:00-07:00',
    resolvedAt: '2026-08-05T15:10:00-07:00',
  },
];

export const ROLE_PERMISSIONS: Record<string, import('../types').RolePermissions> = {
  Admin: {
    canAddServer: true,
    canEditServer: true,
    canDeleteServer: true,
    canAckAlerts: true,
    canResolveAlerts: true,
    canEditThresholds: true,
    canManageTokens: true,
    canTriggerFailover: true,
    canToggleDcMaintenance: true,
    canViewAuditLogs: true,
    canManageUsers: true,
    canExportReports: true,
  },
  Operator: {
    canAddServer: false,
    canEditServer: false,
    canDeleteServer: false,
    canAckAlerts: true,
    canResolveAlerts: true,
    canEditThresholds: false,
    canManageTokens: false,
    canTriggerFailover: false,
    canToggleDcMaintenance: false,
    canViewAuditLogs: true,
    canManageUsers: false,
    canExportReports: true,
  },
  User: {
    canAddServer: false,
    canEditServer: false,
    canDeleteServer: false,
    canAckAlerts: false,
    canResolveAlerts: false,
    canEditThresholds: false,
    canManageTokens: false,
    canTriggerFailover: false,
    canToggleDcMaintenance: false,
    canViewAuditLogs: false,
    canManageUsers: false,
    canExportReports: true,
  },
};

export interface MockAccount {
  id: string;
  username: string;
  passwordHash: string; // Plaintext demo verification
  user: import('../types').AuthUser;
}

export const DEMO_ACCOUNTS: MockAccount[] = [
  {
    id: 'usr-admin-01',
    username: 'admin',
    passwordHash: 'admin123',
    user: {
      id: 'usr-admin-01',
      username: 'admin',
      name: 'Tizita Zewdu (Super Admin)',
      email: 'admin@itdb.gov.et',
      role: 'Admin',
      roleTitle: 'Chief Infrastructure Controller',
      department: 'Ministry of Innovation & Technology / GovIT Operations',
      phone: '+251 91 123 4567',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
      twoFactorEnabled: true,
      lastLogin: '2026-08-19T06:50:00-07:00',
      ipAddress: '10.200.4.15',
      permissions: ROLE_PERMISSIONS['Admin'],
    },
  },
  {
    id: 'usr-operator-01',
    username: 'operator',
    passwordHash: 'operator123',
    user: {
      id: 'usr-operator-01',
      username: 'operator',
      name: 'Kassahun Yimer',
      email: 'kassahun.y@itdb.gov.et',
      role: 'Operator',
      roleTitle: 'Tier-2 NOC Systems Operator',
      department: 'National Data Center Operations Group',
      phone: '+251 92 884 1920',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
      twoFactorEnabled: true,
      lastLogin: '2026-08-19T06:15:00-07:00',
      ipAddress: '10.200.6.12',
      permissions: ROLE_PERMISSIONS['Operator'],
    },
  },
  {
    id: 'usr-user-01',
    username: 'user',
    passwordHash: 'user123',
    user: {
      id: 'usr-user-01',
      username: 'user',
      name: 'Commander Girma',
      email: 'girma.c@police.gov.et',
      role: 'User',
      roleTitle: 'Federal Security & Compliance Auditor',
      department: 'Federal Police Commission / IT Oversight',
      phone: '+251 94 330 9182',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
      twoFactorEnabled: false,
      lastLogin: '2026-08-19T05:30:00-07:00',
      ipAddress: '10.200.12.9',
      permissions: ROLE_PERMISSIONS['User'],
    },
  },
];

export const INITIAL_SESSIONS: import('../types').UserSession[] = [
  {
    sessionId: 'sess-adm-991',
    userId: 'usr-admin-01',
    username: 'admin',
    name: 'Tizita Zewdu (Super Admin)',
    role: 'Admin',
    ipAddress: '10.200.4.15',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0',
    loginTime: '2026-08-19T06:50:00-07:00',
    lastActive: 'Just now',
    currentPage: 'System Settings (#/settings)',
    status: 'Active',
  },
  {
    sessionId: 'sess-opr-412',
    userId: 'usr-operator-01',
    username: 'operator',
    name: 'Kassahun Yimer',
    role: 'Operator',
    ipAddress: '10.200.6.12',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64) Firefox/128.0',
    loginTime: '2026-08-19T06:15:00-07:00',
    lastActive: '5 mins ago',
    currentPage: 'Server Inventory (#/inventory)',
    status: 'Active',
  },
  {
    sessionId: 'sess-usr-203',
    userId: 'usr-user-01',
    username: 'user',
    name: 'Commander Girma',
    role: 'User',
    ipAddress: '10.200.12.9',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1',
    loginTime: '2026-08-19T05:30:00-07:00',
    lastActive: '25 mins ago',
    currentPage: 'Backup Center (#/backup)',
    status: 'Idle',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    user: 'Tizita Zewdu (Super Admin)',
    role: 'Admin',
    action: 'Acknowledge Alert',
    resource: 'Alert #alt-104 (gov-portal-prod-01)',
    ipAddress: '10.200.4.15',
    timestamp: '2026-08-19T06:40:00-07:00',
    status: 'Success',
    changeType: 'ALERT_ACTION',
    targetRoute: '#/alerts-logs',
    details: 'Acknowledged disk space warning and assigned ticket #TICK-8841',
    previousState: { status: 'Active', acknowledgedBy: null },
    newState: { status: 'Acknowledged', acknowledgedBy: 'Tizita Zewdu (Super Admin)' },
    deviceInfo: 'Chrome 126 / Windows 11',
  },
  {
    id: 'aud-002',
    user: 'Tizita Zewdu (Super Admin)',
    role: 'Admin',
    action: 'Update Thresholds',
    resource: 'Global System Thresholds',
    ipAddress: '10.200.4.15',
    timestamp: '2026-08-19T06:22:00-07:00',
    status: 'Success',
    changeType: 'UPDATE',
    targetRoute: '#/settings',
    details: 'Updated Disk Usage Warning Limit from 80% to 85% and CPU limit to 80%',
    previousState: { diskUsageLimitPct: 80, cpuUsageLimitPct: 75 },
    newState: { diskUsageLimitPct: 85, cpuUsageLimitPct: 80 },
    deviceInfo: 'Chrome 126 / Windows 11',
  },
  {
    id: 'aud-003',
    user: 'Kassahun Yimer',
    role: 'Operator',
    action: 'Navigate to Data Centers',
    resource: 'Data Centers View',
    ipAddress: '10.200.6.12',
    timestamp: '2026-08-19T06:16:00-07:00',
    status: 'Success',
    changeType: 'PAGE_VISIT',
    targetRoute: '#/datacenters',
    details: 'User navigated to 10 Data Centers Operations hub',
    deviceInfo: 'Firefox 128 / Ubuntu Linux',
  },
  {
    id: 'aud-004',
    user: 'Kassahun Yimer',
    role: 'Operator',
    action: 'Trigger Ping Test',
    resource: 'Server tax-app-win-01 (192.168.1.132)',
    ipAddress: '10.200.6.12',
    timestamp: '2026-08-19T06:14:00-07:00',
    status: 'Success',
    changeType: 'SYSTEM',
    targetRoute: '#/inventory',
    details: 'Ping test completed: 4 packets sent, 4 received (avg 2.1ms)',
    deviceInfo: 'Firefox 128 / Ubuntu Linux',
  },
  {
    id: 'aud-005',
    user: 'Commander Girma',
    role: 'User',
    action: 'Navigate to Backup Center',
    resource: 'Backup Center View',
    ipAddress: '10.200.12.9',
    timestamp: '2026-08-19T05:32:00-07:00',
    status: 'Success',
    changeType: 'PAGE_VISIT',
    targetRoute: '#/backup',
    details: 'Auditor inspected automated backup logs and compliance table',
    deviceInfo: 'Safari 17 / macOS',
  },
  {
    id: 'aud-006',
    user: 'Tizita Zewdu (Super Admin)',
    role: 'Admin',
    action: 'Generate Agent Token',
    resource: 'Server police-cad-db-01 (192.168.4.99)',
    ipAddress: '10.200.4.15',
    timestamp: '2026-08-19T05:10:00-07:00',
    status: 'Success',
    changeType: 'SECURITY',
    targetRoute: '#/settings',
    details: 'Regenerated cryptographic Bearer authentication token for agent collector',
    previousState: { token: 'agt_tok_old_9988ff442211' },
    newState: { token: 'agt_tok_new_882199aa4411' },
    deviceInfo: 'Chrome 126 / Windows 11',
  },
  {
    id: 'aud-007',
    user: 'External Guest (Unauthorized)',
    role: 'Anonymous',
    action: 'Failed Login Attempt',
    resource: 'POST /api/v1/auth/login',
    ipAddress: '197.156.92.14',
    timestamp: '2026-08-19T04:45:00-07:00',
    status: 'Denied',
    changeType: 'AUTH',
    targetRoute: '#/login',
    details: 'Authentication failure: Bad password hash for user "root". Access blocked.',
    deviceInfo: 'Python-urllib/3.10',
  },
  {
    id: 'aud-008',
    user: 'Kassahun Yimer',
    role: 'Operator',
    action: 'Add Server',
    resource: 'Server customs-api-node-03 (10.200.4.40)',
    ipAddress: '10.200.6.12',
    timestamp: '2026-08-19T04:15:00-07:00',
    status: 'Success',
    changeType: 'CREATE',
    targetRoute: '#/inventory',
    details: 'Created and enrolled new RedHat Enterprise Linux server for Customs department',
    newState: { name: 'customs-api-node-03', ip: '10.200.4.40', type: 'Application', dc: 'DC-04' },
    deviceInfo: 'Firefox 128 / Ubuntu Linux',
  },
  {
    id: 'aud-009',
    user: 'Tizita Zewdu (Super Admin)',
    role: 'Admin',
    action: 'Toggle DC Maintenance',
    resource: 'Data Center Hawassa Industrial DC (DC-03)',
    ipAddress: '10.200.4.15',
    timestamp: '2026-08-19T03:50:00-07:00',
    status: 'Warning',
    changeType: 'UPDATE',
    targetRoute: '#/datacenters',
    details: 'Switched facility mode to Maintenance for cooling system overhaul',
    previousState: { status: 'Healthy' },
    newState: { status: 'Maintenance' },
    deviceInfo: 'Chrome 126 / Windows 11',
  },
];

export const INITIAL_SYSTEM_LOGS: SystemLog[] = [
  {
    id: 'log-sys-001',
    level: 'INFO',
    component: 'AgentCollector',
    serverId: 'srv-001',
    serverName: 'gov-portal-prod-01',
    message: 'Telemetry metrics received via agent Bearer token handshake (CPU: 42%, Mem: 58%, Disk: 64%).',
    timestamp: '2026-08-19T06:49:12-07:00',
  },
  {
    id: 'log-sys-002',
    level: 'WARN',
    component: 'AlertManager',
    serverId: 'srv-002',
    serverName: 'fin-db-cluster-node2',
    message: 'CPU usage threshold breach triggered: 94% exceeds limit 80%. High query lock queue detected.',
    timestamp: '2026-08-19T06:48:30-07:00',
  },
  {
    id: 'log-sys-003',
    level: 'ERROR',
    component: 'BackupEngine',
    serverId: 'srv-002',
    serverName: 'fin-db-cluster-node2',
    message: 'Scheduled incremental snapshot failed: S3 connection timeout after 3 retries.',
    timestamp: '2026-08-19T06:45:00-07:00',
  },
  {
    id: 'log-sys-004',
    level: 'INFO',
    component: 'AuthService',
    message: 'Admin session authenticated successfully for user "admin" (IP: 10.200.4.15).',
    timestamp: '2026-08-19T06:40:15-07:00',
  },
  {
    id: 'log-sys-005',
    level: 'WARN',
    component: 'PortalAPI',
    serverId: 'srv-004',
    serverName: 'health-records-file01',
    message: 'Disk volume /dev/sdb1 capacity warning: 91% utilized (Threshold 85%).',
    timestamp: '2026-08-19T06:30:22-07:00',
  },
  {
    id: 'log-sys-006',
    level: 'DEBUG',
    component: 'AgentCollector',
    serverId: 'srv-005',
    serverName: 'ethio-dns-core-01',
    message: 'DNS server health heartbeat ping OK (latency 1.2ms, status 200).',
    timestamp: '2026-08-19T06:25:00-07:00',
  },
  {
    id: 'log-sys-007',
    level: 'ERROR',
    component: 'AuthService',
    message: 'Failed authentication attempt for unauthorized account "root" from 197.156.92.14.',
    timestamp: '2026-08-19T04:45:00-07:00',
  },
  {
    id: 'log-sys-008',
    level: 'INFO',
    component: 'BackupEngine',
    serverId: 'srv-001',
    serverName: 'gov-portal-prod-01',
    message: 'Daily incremental backup completed successfully (Size: 450.2 GB, Duration: 14m 20s).',
    timestamp: '2026-08-19T03:00:00-07:00',
  },
];

export const INITIAL_THRESHOLDS: ThresholdSettings = {
  diskUsageLimitPct: 85,
  cpuUsageLimitPct: 80,
  memoryUsageLimitPct: 85,
  backupFailureTimeoutHours: 24,
  emailAlertsEnabled: true,
  slackAlertsEnabled: true,
  smsAlertsEnabled: false,
  alertRecipientEmails: ['noc-alerts@itdb.gov.et', 'infrastructure-leads@gov.et'],
  pingIntervalSeconds: 30,
  ipRestrictionEnabled: true,
  allowedSubnet: '10.200.0.0/16',
};

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr-admin-01',
  name: 'Tizita Zewdu',
  email: 'admin@itdb.gov.et',
  role: 'Super Admin',
  department: 'Ministry of Innovation & Technology / GovIT Operations',
  phone: '+251 91 123 4567',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
  twoFactorEnabled: true,
  lastLogin: '2026-08-19T06:50:00-07:00',
};

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'ALERT',
    title: 'POST Failure',
    description: 'POST /servers/memory request failed on fin-db-cluster-node2',
    timestamp: '2026-08-06T04:12:00-07:00',
    severity: 'Critical',
    serverName: 'fin-db-cluster-node2',
  },
  {
    id: 'act-002',
    type: 'BACKUP',
    title: 'Backup Failed',
    description: 'Incremental backup failed on fin-db-cluster-node2',
    timestamp: '2026-08-06T03:45:00-07:00',
    severity: 'Critical',
    serverName: 'fin-db-cluster-node2',
  },
  {
    id: 'act-003',
    type: 'ALERT',
    title: 'Disk Warning (>85%)',
    description: 'Disk utilization reached 91% on health-records-file01',
    timestamp: '2026-08-06T02:30:00-07:00',
    severity: 'Warning',
    serverName: 'health-records-file01',
  },
  {
    id: 'act-004',
    type: 'SYSTEM',
    title: 'Agent Token Verified',
    description: 'Agent token validated for ethio-dns-core-01',
    timestamp: '2026-08-06T01:00:00-07:00',
    severity: 'Info',
    serverName: 'ethio-dns-core-01',
  },
  {
    id: 'act-005',
    type: 'USER',
    title: 'Thresholds Updated',
    description: 'Tizita Zewdu updated disk alert limit to 85%',
    timestamp: '2026-08-05T22:15:00-07:00',
    severity: 'Info',
  },
];

export const TELEMETRY_DATA: TelemetryPoint[] = [
  { time: '10:00', cpuAverage: 42, cpuHighCritical: 82, memoryAverage: 58, diskAverage: 62 },
  { time: '11:00', cpuAverage: 48, cpuHighCritical: 84, memoryAverage: 61, diskAverage: 63 },
  { time: '12:00', cpuAverage: 55, cpuHighCritical: 88, memoryAverage: 68, diskAverage: 63 },
  { time: '13:00', cpuAverage: 39, cpuHighCritical: 79, memoryAverage: 64, diskAverage: 64 },
  { time: '14:00', cpuAverage: 62, cpuHighCritical: 91, memoryAverage: 72, diskAverage: 64 },
  { time: '15:00', cpuAverage: 58, cpuHighCritical: 89, memoryAverage: 71, diskAverage: 65 },
  { time: '16:00', cpuAverage: 71, cpuHighCritical: 94, memoryAverage: 79, diskAverage: 65 },
  { time: '17:00', cpuAverage: 45, cpuHighCritical: 82, memoryAverage: 69, diskAverage: 66 },
  { time: '18:00', cpuAverage: 50, cpuHighCritical: 85, memoryAverage: 70, diskAverage: 66 },
];

export const BACKUP_TRENDS: BackupHistoryPoint[] = [
  { date: 'Jul 31', successful: 118, failed: 2, inProgress: 0, totalSizeTB: 12.4 },
  { date: 'Aug 01', successful: 119, failed: 1, inProgress: 0, totalSizeTB: 12.6 },
  { date: 'Aug 02', successful: 120, failed: 0, inProgress: 0, totalSizeTB: 12.8 },
  { date: 'Aug 03', successful: 117, failed: 3, inProgress: 0, totalSizeTB: 12.9 },
  { date: 'Aug 04', successful: 118, failed: 2, inProgress: 0, totalSizeTB: 13.1 },
  { date: 'Aug 05', successful: 116, failed: 3, inProgress: 1, totalSizeTB: 13.4 },
  { date: 'Aug 06', successful: 117, failed: 2, inProgress: 1, totalSizeTB: 13.6 },
];
